php:
    build: env/docker/php
    command: "php -S 0.0.0.0:8000"
    working_dir: /var/www/html/public
    volumes_from:
        - filesystem
    ports:
        - "80:8000"
filesystem:
    image: debian:jessie
    volumes:
        - ./:/var/www/html/
        - ~/.composer/:/root/.composer/ # leverage host compoaser cache while building
