php:
    build: config/docker/php
    command: "php -S 0.0.0.0:8000"
    volumes_from:
        - filesystem
    ports:
        - "80:8000"
filesystem:
    image: debian:jessie
    volumes:
        - ./:/var/www/html/
          #        - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ~/.composer/:/root/.composer/ # leverage host compoaser cache while building
